baseURL = 'https://MarcosCamp.github.io/Practica2_Hugo_Marcos/'
languageCode = 'en-us'
title = 'Inicio'
theme="hugo-theme-stack"
[params]
logo = "/images/avatar_hu13739649187745961479.png"
  mainSections = ["content"]


[menu]

  [[menu.main]]
    name = "Markdown"
    url = "/markdown/"
    weight = 1

  [[menu.main]]
    name = "Imagenes"
    url = "/imagenes/"
    weight = 2

  [[menu.main]]
    name = "Tv"
    url = "/tv/"
    weight = 3


  [[menu.main]]
    name = "Python"
    url = "/python/"
    weight = 4

 [[menu.main]]
    name = ""
    url = "/vacio/"
    weight = 5
