baseURL = 'https://marcoscamp.github.io/Practica2_Hugo_Marcos/'
languageCode = 'en-us'
title = 'Inicio'
theme="hugo-theme-stack"
[params]
logo = "/images/avatar_hu13739649187745961479.png"
  mainSections = ["content"]


[menu]

  [[menu.main]]
    name = "Markdown Basico"
    url = "/markdownB/"
    weight = 1

  [[menu.main]]
    name = "Markdown Extendido"
    url = "/markdownE/"
    weight = 2

    [[menu.main]]
    name = "Markdown Grafico"
    url = "/markdownG/"
    weight = 3
  [[menu.main]]
    name = "Imagenes"
    url = "/imagenes/"
    weight = 4

  [[menu.main]]
    name = "Tv"
    url = "/tv/"
    weight = 5


  [[menu.main]]
    name = "Python"
    url = "/python/"
    weight = 6

 [[menu.main]]
    name = "tablas markdown"
    url = "/tablas/"
    weight = 7

